name: Sync Submodule

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Update submodules
        run: |
          git submodule init
          git submodule update --remote --rebase
