name: Sync Submodule

on:
  schedule:
    - cron: '0 * * * *'  # каждый час
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Update submodules
        run: |
          git submodule update --init --recursive --remote
          git add _posts/posts-repo
          git commit -m "Auto-update posts submodule"
          git push
